### ISSUE TITLE
CoreMod?

### ISSUE THREAD

**Issue by Darkhax** [rwtema/DietHopper#1]
I am curious why you made this a core mod. Couldn't you just replace the original hopper block with a wrapped version that has the corrected bounds?

**Comment by DaemonUmbra** [comment]
From my rather wet-behind-the-ears point of view to modding, replacement of blocks is not as smooth as you might think, and might lead to incompatibilities with mods that want to use the vanilla hopper in recipes or multiblock structures.
Note: again I'm wet behind the ears, so I might be incorrect

**Comment by rwtema** [comment]
I completely forgot you could replace blocks. I'll look into it.

**Comment by rwtema** [comment]
Replaced core mod with wrapped block

**Comment by DaemonUmbra** [comment]
Lex would be proud
